
package com.cst438.controller;

import com.cst438.domain.Assignment;
import com.cst438.domain.AssignmentRepository;
import com.cst438.domain.Enrollment;
import com.cst438.domain.EnrollmentRepository;
import com.cst438.domain.Grade;
import com.cst438.domain.GradeRepository;
import com.cst438.domain.Section;
import com.cst438.domain.SectionRepository;
import com.cst438.domain.User;
import com.cst438.domain.UserRepository;
import com.cst438.dto.GradeDTO;
import com.cst438.dto.LoginDTO;
import com.cst438.service.RegistrarServiceProxy;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.reactive.server.EntityExchangeResult;
import org.springframework.test.web.reactive.server.WebTestClient;

import java.sql.Date;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class GradeControllerUnitTest {

    @Autowired
    private WebTestClient client;

    @Autowired
    private AssignmentRepository assignmentRepository;

    @Autowired
    private GradeRepository gradeRepository;

    @Autowired
    private EnrollmentRepository enrollmentRepository;

    @Autowired
    private SectionRepository sectionRepository;

    @Autowired
    private UserRepository userRepository;

    @MockitoBean
    private RegistrarServiceProxy registrarServiceProxy;

    @Test
    public void getAssignmentGradesAndUpdateGrades() {

        /*
         * The starter data contains:
         * instructor: ted@csumb.edu / ted
         * student:    sam@csumb.edu
         * section:    section_no = 1
         */

        String jwt = loginAsInstructor();

        Section section = sectionRepository.findById(1).orElse(null);
        User student = userRepository.findByEmail("sam@csumb.edu");

        assertNotNull(section, "Test section 1 was not found.");
        assertNotNull(student, "Test student sam@csumb.edu was not found.");

        /*
         * Enrollment IDs come from the Registrar service, so the ID is
         * assigned manually instead of being generated by the database.
         */
        Enrollment enrollment = new Enrollment();
        enrollment.setEnrollmentId(9001);
        enrollment.setSection(section);
        enrollment.setStudent(student);
        enrollment.setGrade(null);
        enrollmentRepository.save(enrollment);

        Assignment assignment = new Assignment();
        assignment.setSection(section);
        assignment.setTitle("GradeController Unit Test");
        assignment.setDueDate(Date.valueOf("2026-10-15"));
        assignment = assignmentRepository.save(assignment);

        int assignmentId = assignment.getAssignmentId();

        /*
         * GET should return every student enrolled in the section.
         * Since this student has no Grade entity yet, the controller should
         * create one with a null score.
         */
        EntityExchangeResult<GradeDTO[]> getResult = client.get()
                .uri("/assignments/{assignmentId}/grades", assignmentId)
                .headers(headers -> headers.setBearerAuth(jwt))
                .accept(MediaType.APPLICATION_JSON)
                .exchange()
                .expectStatus().isOk()
                .expectBody(GradeDTO[].class)
                .returnResult();

        GradeDTO[] grades = getResult.getResponseBody();

        assertNotNull(grades);
        assertEquals(1, grades.length);

        GradeDTO createdGrade = grades[0];

        assertEquals("sam@csumb.edu", createdGrade.studentEmail());
        assertEquals(
                "GradeController Unit Test",
                createdGrade.assignmentTitle()
        );
        assertEquals("cst489", createdGrade.courseId());
        assertEquals(1, createdGrade.sectionId());
        assertNull(
                createdGrade.score(),
                "A newly created grade should have a null score."
        );

        Grade gradeInDatabase =
                gradeRepository.findById(createdGrade.gradeId()).orElse(null);

        assertNotNull(
                gradeInDatabase,
                "GET should create the missing Grade entity."
        );
        assertNull(gradeInDatabase.getScore());

        /*
         * PUT should change the score of the Grade entity created above.
         */
        GradeDTO updatedGrade = new GradeDTO(
                createdGrade.gradeId(),
                createdGrade.studentName(),
                createdGrade.studentEmail(),
                createdGrade.assignmentTitle(),
                createdGrade.courseId(),
                createdGrade.sectionId(),
                92
        );

        client.put()
                .uri("/grades")
                .headers(headers -> headers.setBearerAuth(jwt))
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(List.of(updatedGrade))
                .exchange()
                .expectStatus().isOk();

        gradeInDatabase =
                gradeRepository.findById(createdGrade.gradeId()).orElse(null);

        assertNotNull(gradeInDatabase);
        assertEquals(92, gradeInDatabase.getScore());

        /*
         * Clean up records created by this test.
         * Grade must be deleted before its assignment and enrollment.
         */
        gradeRepository.deleteById(createdGrade.gradeId());
        assignmentRepository.deleteById(assignmentId);
        enrollmentRepository.deleteById(enrollment.getEnrollmentId());
    }

    private String loginAsInstructor() {

        EntityExchangeResult<LoginDTO> loginResult = client.get()
                .uri("/login")
                .headers(headers ->
                        headers.setBasicAuth("ted@csumb.edu", "ted"))
                .accept(MediaType.APPLICATION_JSON)
                .exchange()
                .expectStatus().isOk()
                .expectBody(LoginDTO.class)
                .returnResult();

        LoginDTO login = loginResult.getResponseBody();

        assertNotNull(login);
        assertNotNull(login.jwt());

        return login.jwt();
    }
}
